name: main

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'

  workflow_dispatch:

jobs:
  tii-deb-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros2_distro: [ humble ]
    steps:
      - name: Checkout fog_msgs
        uses: actions/checkout@v2
        with:
          path: fog_msgs
      # Run docker build
      - name: Run fog-msgs docker build
        env:
          ROS: 1
          PACKAGE_NAME: fog_msgs
        run: |
          set -eux
          mkdir bin
          pushd fog_msgs
          ./build.sh ../bin/
          popd
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: fog_msgs
          path: bin/*.deb
          retention-days: 1

      - name: Upload to Artifactory
        uses: actions/upload-artifact@v2
        with:
          name: fog_msgs
          path: bin/build_output/*.deb
          retention_days: 1

  artifactory:
    runs-on: ubuntu-latest
    needs: tii-deb-build
    if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
          path: bin/build_output
      - uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_ARTIFACTORY_1: ${{ secrets.ARTIFACTORY_TOKEN }}
      - name: Upload to Artifactory
        env:
          ARTIFACTORY_REPO: ssrc-deb-public-local
          DISTRIBUTION: jammy
          COMPONENT: fog-sw
          ARCHITECTURE: amd64
          BUILD_NAME: fog_msgs
          CI: true
        run: |
          set -exu
          jfrog rt ping
          for pkg in bin/build_output/*.deb
          do
            pkg_name=$(basename $pkg)
            jfrog rt u --deb "$DISTRIBUTION/$COMPONENT/$ARCHITECTURE" \
                       --target-props COMMIT="$GITHUB_SHA" \
                       --build-name "$BUILD_NAME" \
                       --build-number "$GITHUB_SHA" \
                       "$pkg" \
                       "$ARTIFACTORY_REPO/$pkg_name"
          done
          jfrog rt build-publish "$BUILD_NAME" "$GITHUB_SHA"
          jfrog rt bpr "$BUILD_NAME" "$GITHUB_SHA" "$ARTIFACTORY_REPO" \
                       --status dev \
                       --comment "development build"
